### ISSUE TITLE
Dashboard

### ISSUE THREAD

**Issue by dionew1** [RyanDBarnett/viewing_party#13]
As an authenticated user,
When I visit '/dashboard'
I should see: 
- [x] 'Welcome `<username>`!' at the top of page
- [x] #9  A button to Discover Movies
- [x] #10 A friends section
- [x] #11 A viewing parties section

**Comment by ryandbarnett** [comment]
Added a sad path test for when a non authenticated user visits /dashboard. They are redirected to the log in page and given a notice that they need to log in before they can visit their dashboard.
