### ISSUE TITLE
PARTY / NEW PARTY refactor

### ISSUE THREAD

**Issue by aetzion1** [RyanDBarnett/viewing_party#76]
WHO IS WORING ON THIS?
- [x] Should not pass in parameters / have hidden fields. Throw title, id, duration into session. Then pull out of the session when in form and then when creating pull again.
- [x] Duration: check validation. In new form, make it a number field , or set min and max values (set min to be duration as well as the value) 
- [x] Friend checkboxes:Make checkboxes and names line up

**Comment by ryandbarnett** [comment]
Blocked on new party refactor. I'm trying to make a sad path test for when a user successfully submits a new party form but then hits the back button and submits again.
I can't seem to find an easy way to simulate hitting the browser back button
What I have looked at suggests I need to simulate the browser with 3+ gems
